### ISSUE TITLE
pre talk finishing touches

### ISSUE THREAD

**Issue by CircArgs** [KnowledgeForge/headjack#65]
- [x] Search agents use multiple different queries
- [x] chat typing animation with pills for agent mentions 
- [x] agent note passing
- [x] utterance always str; metadata attribute
- [x] the people page isn't showing the people but not sure yet why that is in case you want to look into that.
- [x] the metrics page still doesn't do anything
- [x] the chat doesn't show results from people search
- [ ] the chat doesn't show results from message search
- [x] @samredai docs deploy to headjack.dev domain
- [x] fix plot duping data
- [x] chat should autoscroll to bottom on overflow
- [ ] llm selection via api and ui
- [ ] fix typing animation on chat sometimes loops on metadata utterances when user types
- [ ] DOCS! (i.e. running a custom Headjack Search Service)
- [ ] Recording

**Comment by samredai** [comment]
Here are the instructions to configure headjack.dev to point to the netlify app:
![image](https://github.com/KnowledgeForge/headjack/assets/43911210/100156af-771e-4aa8-bf08-e6f5ca44d565)
Once you set that in the domain settings it should all work within a few minutes.
